version: "3.8"

services:
  app:
    image: app:local
    ports:
      - "8080:8080"
    depends_on:
      - mongo1
      - migrate
    command:  serve --config config.yaml

  migrate:
    image: app:local
    depends_on:
      - mongo1
    command:  migrate up --config config.yaml

  mongo1:
    image: mongo:7.0
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"

  mongo-express:
    image: "mongo-express"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://host.docker.internal:27017/?replicaSet=rs0&authSource=admin"
      ME_CONFIG_BASICAUTH_USERNAME: user
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongo1
    ports:
      - "8081:8081"

volumes:
  mongo1_data:
  mongo1_config: